services:
  - type: web
    name: marketing-report-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: LLAMA_API_KEY
        sync: false
      - key: base_url
        sync: false